---
# tasks file for jjs

- apt: update_cache=yes upgrade=yes
  sudo: yes
- apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - git
    - nginx
    - python-pip
    - libssl-dev
    - libffi-dev
    - python2.7-dev
    - python3.4-dev
- pip: state=latest name={{ item }}
  sudo: yes
  with_items:
    - pip
    - virtualenv
    - setuptools
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn
    - tox
- git: repo={{ jjs_source_location }} dest=src/jenkins-job-scraper
- pip: name='~/src/jenkins-job-scraper' virtualenv=~/jjs-venv state="latest"
- synchronize: src='conf' dest='~/jjs-venv'
- file: path="~/data" state="directory" owner="{{ ansible_user_id }}"
- file: path="~/bin" state="directory" owner="{{ ansible_user_id }}"
- file: path="/usr/share/nginx/html/reports" state="directory" owner="{{ ansible_user_id }}" mode=755
  sudo: yes
- copy: dest="~/bin/scrape-all-jobs.sh" src="scrape-all-jobs.sh" owner="{{ ansible_user_id }}" mode=0544
- cron: name='get data' user="{{ ansible_user_id }}" minute="*/15" job="~/bin/scrape-all-jobs.sh ~/jjs-venv ~/jjs-venv/conf ~/data /usr/share/nginx/html/reports"
- apt: name=nginx state=present
  sudo: yes
- template: src=default dest=/etc/nginx/sites-available/default
  sudo: yes
  notify: reload nginx

